2025-04-25 16:22:12,663 ERROR: Exception on /login [GET] [in D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\Administrator\montyu\microblog\app\routes.py", line 48, in login
    return render_template('login.html', title='Sign In', form=form)
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "D:\anaconda\envs\flaskenv\lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "D:\anaconda\envs\flaskenv\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Administrator\montyu\microblog\app\templates\login.html", line 2, in top-level template code
    {% import "bootstrap_wtf.html" as wtf %}
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bootstrap_wtf.html
2025-04-25 16:25:16,477 ERROR: Exception on /login [GET] [in D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\Administrator\montyu\microblog\app\routes.py", line 48, in login
    return render_template('login.html', title='Sign In', form=form)
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "D:\anaconda\envs\flaskenv\lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "D:\anaconda\envs\flaskenv\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Administrator\montyu\microblog\app\templates\login.html", line 2, in top-level template code
    {% import "bootstrap_wtf.html" as wtf %}
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bootstrap_wtf.html
2025-04-25 16:26:34,657 INFO: Microblog startup [in C:\Users\Administrator\montyu\microblog\app\__init__.py:35]
2025-04-25 16:26:35,722 ERROR: Exception on /login [GET] [in D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\Administrator\montyu\microblog\app\routes.py", line 48, in login
    return render_template('login.html', title='Sign In', form=form)
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "D:\anaconda\envs\flaskenv\lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "D:\anaconda\envs\flaskenv\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Administrator\montyu\microblog\app\templates\login.html", line 2, in top-level template code
    {% import "bootstrap_wtf.html" as wtf %}
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "D:\anaconda\envs\flaskenv\lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bootstrap_wtf.html
2025-04-25 16:27:48,404 INFO: Microblog startup [in C:\Users\Administrator\montyu\microblog\app\__init__.py:35]
2025-04-28 15:33:55,368 INFO: Microblog startup [in C:\Users\Administrator\montyu\microblog\app\__init__.py:35]
2025-04-28 15:35:41,414 INFO: Microblog startup [in C:\Users\Administrator\montyu\microblog\app\__init__.py:35]
2025-04-28 15:36:37,663 INFO: Microblog startup [in C:\Users\Administrator\montyu\microblog\app\__init__.py:35]
2025-04-28 15:39:42,096 INFO: Microblog startup [in C:\Users\Administrator\montyu\microblog\app\__init__.py:35]
2025-04-28 15:45:18,570 INFO: Microblog startup [in C:\Users\Administrator\montyu\microblog\app\__init__.py:35]
2025-04-28 15:50:07,820 INFO: Microblog startup [in C:\Users\Administrator\montyu\microblog\app\__init__.py:35]
2025-04-28 15:52:08,925 INFO: Microblog startup [in C:\Users\Administrator\montyu\microblog\app\__init__.py:35]
2025-04-28 16:19:04,307 INFO: Microblog startup [in C:\Users\Administrator\montyu\microblog\app\__init__.py:37]
2025-04-29 16:06:38,088 INFO: Microblog startup [in C:\Users\Administrator\montyu\microblog\app\__init__.py:40]
2025-04-29 16:09:52,814 INFO: Microblog startup [in C:\Users\Administrator\montyu\microblog\app\__init__.py:40]
2025-04-29 16:12:17,341 INFO: Microblog startup [in C:\Users\Administrator\montyu\microblog\app\__init__.py:44]
2025-04-29 16:13:56,531 INFO: Microblog startup [in C:\Users\Administrator\montyu\microblog\app\__init__.py:44]
2025-04-29 16:15:22,198 INFO: Microblog startup [in C:\Users\Administrator\montyu\microblog\app\__init__.py:44]
2025-04-29 16:16:40,187 INFO: Microblog startup [in C:\Users\Administrator\montyu\microblog\app\__init__.py:43]
2025-04-29 16:16:58,032 INFO: Microblog startup [in C:\Users\Administrator\montyu\microblog\app\__init__.py:43]
2025-04-29 16:26:57,766 INFO: Microblog startup [in C:\Users\Administrator\montyu\microblog\app\__init__.py:43]
2025-04-29 16:41:16,871 INFO: Microblog startup [in C:\Users\Administrator\montyu\microblog\app\__init__.py:43]
2025-04-29 16:41:47,445 INFO: Microblog startup [in C:\Users\Administrator\montyu\microblog\app\__init__.py:43]
2025-04-29 16:44:05,779 INFO: Microblog startup [in C:\Users\Administrator\montyu\microblog\app\__init__.py:43]
2025-04-29 16:45:26,213 INFO: Microblog startup [in C:\Users\Administrator\montyu\microblog\app\__init__.py:43]
2025-04-29 16:45:30,499 INFO: Microblog startup [in C:\Users\Administrator\montyu\microblog\app\__init__.py:43]
2025-04-29 16:46:33,478 INFO: Microblog startup [in C:\Users\Administrator\montyu\microblog\app\__init__.py:43]
2025-04-29 16:53:04,448 INFO: Microblog startup [in C:\Users\Administrator\montyu\microblog\app\__init__.py:43]
2025-04-29 16:53:10,611 INFO: Microblog startup [in C:\Users\Administrator\montyu\microblog\app\__init__.py:43]
2025-04-29 16:53:33,140 INFO: Microblog startup [in C:\Users\Administrator\montyu\microblog\app\__init__.py:43]
2025-04-29 16:54:08,621 INFO: Microblog startup [in C:\Users\Administrator\montyu\microblog\app\__init__.py:43]
2025-04-29 16:55:12,231 INFO: Microblog startup [in C:\Users\Administrator\montyu\microblog\app\__init__.py:43]
2025-04-29 16:55:34,087 INFO: Microblog startup [in C:\Users\Administrator\montyu\microblog\app\__init__.py:43]
2025-04-29 16:55:42,168 INFO: Microblog startup [in C:\Users\Administrator\montyu\microblog\app\__init__.py:43]
2025-04-29 16:55:53,454 INFO: Microblog startup [in C:\Users\Administrator\montyu\microblog\app\__init__.py:43]
2025-04-29 17:03:52,043 INFO: Microblog startup [in C:\Users\Administrator\montyu\microblog\app\__init__.py:43]
2025-04-29 17:04:11,956 INFO: Microblog startup [in C:\Users\Administrator\montyu\microblog\app\__init__.py:43]
2025-04-29 17:04:22,711 INFO: Microblog startup [in C:\Users\Administrator\montyu\microblog\app\__init__.py:43]
2025-04-29 17:04:53,547 INFO: Microblog startup [in C:\Users\Administrator\montyu\microblog\app\__init__.py:43]
